import asyncio
from typing import Protocol


class ProcessError(Exception):
    """Kullanıcıya gösterilebilir süreç hatası (Java yok, jar yok vb.)."""


class ProcessBackend(Protocol):
    """Süreç yönetimi arayüzü. Şimdilik SubprocessBackend var;
    VDS'te SystemdBackend/TmuxBackend aynı arayüzü uygulayacak."""

    async def start(self, instance: dict) -> None: ...
    async def stop(self, instance_id: int, timeout: int = 60) -> None: ...
    async def kill(self, instance_id: int) -> None: ...
    async def restart(self, instance: dict) -> None: ...
    async def send_command(self, instance_id: int, command: str) -> None: ...
    def is_running(self, instance_id: int) -> bool: ...
    def pid(self, instance_id: int) -> int | None: ...
    def running_ids(self) -> list[int]: ...
    def status(self, instance_id: int) -> str: ...
    def set_status(self, instance_id: int, status: str) -> None: ...
    def emit(self, instance_id: int, msg: dict) -> None: ...
    def log(self, instance_id: int, line: str) -> None: ...
    def progress(self, instance_id: int) -> dict | None: ...
    def notify_error(self, instance_id: int, message: str) -> None: ...
    def history(self, instance_id: int) -> list[str]: ...
    def subscribe(self, instance_id: int) -> asyncio.Queue: ...
    def unsubscribe(self, instance_id: int, queue: asyncio.Queue) -> None: ...
